.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "GOSOP" "1" "November 2022" ""
.SH "NAME"
\fBgosop\fR \- Stateless OpenPGP implementation for GopenPGP
.SH "USAGE:"
gosop [global options] command [command options] [arguments\|\.\|\.\|\.]
.SH "AUTHOR:"
Proton Technologies AG
.SH "COMMANDS"
.TP
\fBarmor\fR:

.P
Add ASCII Armor
.TP
\fBdearmor\fR:

.P
Remove ASCII Armor
.TP
\fBdecrypt\fR:

.P
Decrypt a Message
.TP
\fBencrypt\fR:

.P
Encrypt a Message
.TP
\fBextract\-cert\fR:

.P
Extract a Certificate from a Secret Key
.TP
\fBgenerate\-key\fR:

.P
Generate a Secret Key
.TP
\fBsign\fR:

.P
Create a Detached Signature
.TP
\fBverify\fR:

.P
Verify a Detached Signature
.TP
\fBversion\fR:

.P
Version Information
.TP
\fBhelp\fR, \fBh\fR:

.P
Shows a list of commands or help for one command
.SH "GLOBAL OPTIONS"
.TP
\fB\-\-help\fR, \fB\-h\fR:

.P
Show help (default: false)
